### ISSUE TITLE
RecordOverview constructor fails for jump_jabroni

### ISSUE THREAD

**Issue by laurirasanen** [arispoloway/tempus-api#7]
RecordOverview constructor fails for `jump_jabroni` demoman WR, haven't found any other maps with the same issue.  

Code:  
```js
const tempus = require("tempus-api");

async function main() {
    let dwr = await tempus.mapWR("jump_jabroni", "d");
    console.dir(dwr);
    if (dwr != null) {
        let overview = await dwr.toRecordOverview();
        console.dir(overview);
    }
}

main();

```

Output:  
```
> node .\index.js
Record {
  id: 3878772,
  zone_id: 6720,
  duration: 257.819697856903,
  date: 1592201475.57122,
  user_id: 76244,
  name: 'Hona',
  rank: 1,
  player_info: { steamid: 'STEAM_0:0:130771884', id: 76244, name: 'Hona' },
  player: Player { name: 'Hona', id: 76244, steamid: 'STEAM_0:0:130771884' },
  map: Map { name: 'jump_jabroni' },
  zone_info: ZoneInfo {
    id: 6720,
    map_id: 507,
    type: 'map',
    zoneindex: 1,
    custom_name: null
  }
}
(node:15752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map_name' of null
    at new RecordOverview ([...]\node_modules\tempus-api\lib\models\records.js:57:28)
    at Object.recordOverview ([...]\node_modules\tempus-api\lib\records.js:56:12)
    at async Record.toRecordOverview ([...]\node_modules\tempus-api\lib\models\records.js:47:16)
    at async main ([...]\index.js:7:24)
(node:15752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by arispoloway** [comment]
Hm interesting. Seems like a funny case that happens when there isn't a demo available. We can get the map name from elsewhere in the response, so I should be able to fix at least that portion of it, but the real problem with the record seems to be the missing demo.

**Comment by laurirasanen** [comment]
Weird. https://tempus.xyz/demos/1275958 was definitely linked to the WR at some point because it got uploaded to https://youtu.be/yzYP27Sk8Zg, but I guess something went wrong over the past month or so.

**Comment by arispoloway** [comment]
Weird 🤷 good to close this issue then? Seems like a tempus problem
